# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
project:
  alias: elasticsearch-backend

slack:
  notify_channel: _a2_ha_backend

github:
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Version Major"

pipelines:
  - habitat/build:
      description: Build the component Habitat Packages

merge_actions:
  - trigger_pipeline:habitat/build:
      post_commit: true
      ignore_labels:
        - "Expeditor: Skip All"
        - "Expeditor: Skip Habitat Build"

subscriptions:
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages

# These actions are taken when `/expeditor promote` is run from Slack
promote:
  actions:
    - built_in:promote_habitat_packages
  channels:
    - dev
    - stable
