# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
project:
  alias: opendistro-for-elasticsearch

slack:
  notify_channel: _a2_ha_backend

github:
  delete_branch_on_merge: true
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  major_bump_labels:
    - "Expeditor: Bump Version Major"

pipelines:
  - habitat/build:
      description: Build the component Habitat Packages
  
subscriptions:
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages

  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions: 
      - trigger_pipeline:habitat/build:
          post_commit: true
          ignore_labels:
            - "Expeditor: Skip All"
            - "Expeditor: Skip Habitat Build"   

  # These actions are taken when `/expeditor promote` is run from Slack
  - workload: project_promoted:{{agent_id}}:*
    actions:  
      - built_in:promote_habitat_packages        

artifact_channels:
  - dev
  - stable
