#=========================== Journalbeat inputs ================================

[["journalbeat.inputs"]]
paths = []

#================================ Outputs ======================================

["output.elasticsearch"]
hosts = [
  "localhost:9200"
]
